using SoulsFormats;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SoulsAssetPipeline.Animation
{
    public partial class TAE : SoulsFile<TAE>
    {
        /// <summary>
        /// An action triggered at a certain time during an animation.
        /// </summary>
        public class Action
        {
            public TAE.ActionTrack DS1AutoGeneratedTrack = null;
            //public int Row;

            /// <summary>
            /// The type of this action.
            /// </summary>
            public int Type { get; private set; }

            public void ForceChangeType(int newType)
            {
                Type = newType;
            }


            /// <summary>
            /// TAE Action Track which contains this action.
            /// </summary>
            public int TrackIndex { get; set; } = -1;

            /// <summary>
            /// An unknown 32-bit integer following the action type.
            /// So far confirmed to be used in SOTFS and SDT
            /// </summary>
            public int Unk04 { get; private set; }

            /// <summary>
            /// When the action begins.
            /// </summary>
            public float StartTime;

            /// <summary>
            /// When the action ends.
            /// </summary>
            public float EndTime;

            public BinaryReaderEx GetParamBinReader(bool bigEndian)
            {
                return new BinaryReaderEx(bigEndian, ParameterBytes);
            }


            public const float EldenRingInfiniteLengthEventPlaceholder = 100;

            public float MemeEndTime => EndTime >= EldenRingInfiniteLengthEventPlaceholder ? float.MaxValue : EndTime;

            public byte[] ParameterBytes;

            /// <summary>
            /// Creates a new action with the specified start time, end time, type, unknown, and parameters.
            /// </summary>
            public Action(float startTime, float endTime, int type, int unk04, byte[] parameters)
            {
                StartTime = startTime;
                EndTime = endTime;
                Type = type;
                Unk04 = unk04;
                ParameterBytes = parameters;
            }

            internal Action(float startTime, float endTime)
            {
                StartTime = startTime;
                EndTime = endTime;
            }

            internal void WriteHeader(BinaryWriterEx bw, int animIndex, int actionIndex, Dictionary<float, long> timeOffsets, TAEFormat format)
            {
                bw.WriteVarint(timeOffsets[StartTime]);
                bw.WriteVarint(timeOffsets[MemeEndTime]);
                bw.ReserveVarint($"ActionDataOffset{animIndex}:{actionIndex}");
                if (format is TAEFormat.DES or TAEFormat.DESR) // Not sure if in DESR
                    bw.Pad(0x10);
            }

            internal void WriteData(BinaryWriterEx bw, int animIndex, int actionIndex, TAEFormat format)
            {
                //CopyParametersToBytes(bw.BigEndian);

                bw.FillVarint($"ActionDataOffset{animIndex}:{actionIndex}", bw.Position);
                bw.WriteInt32(Type);

                if (bw.VarintLong)
                    bw.WriteInt32(Unk04);

                bool isWeirdActionWithNoParamOffset = format == TAEFormat.SDT && Type == 943;

                if (isWeirdActionWithNoParamOffset)
                    bw.WriteVarint(0);
                else
                    bw.ReserveVarint($"ActionDataParametersOffset{animIndex}:{actionIndex}");

                if (format is TAEFormat.DES) // Not in DESR
                {
                    bw.WriteInt32(0);
                    bw.WriteInt32(0);
                    //bw.Pad(0x10);
                }

                if (!isWeirdActionWithNoParamOffset)
                    bw.FillVarint($"ActionDataParametersOffset{animIndex}:{actionIndex}", bw.Position);

                bw.WriteBytes(ParameterBytes);

                if (bw.VarintLong || format is TAEFormat.DES)
                    bw.Pad(0x10);
            }

            internal void ReadParameters(BinaryReaderEx br, int byteCount)
            {
                ParameterBytes = br.ReadBytes(byteCount);
            }

            /// <summary>
            /// Returns the start time, end time, and type of the action.
            /// </summary>
            public override string ToString()
            {
                return $"{(int)Math.Round(StartTime * 30):D3} - {(int)Math.Round(EndTime * 30):D3} {Type}";
            }

            internal static Action Read(BinaryReaderEx br, out long parametersOffset, TAEFormat format)
            {
                long startTimeOffset = br.ReadVarint();
                long endTimeOffset = br.ReadVarint();
                long actionDataOffset = br.ReadVarint();

                if (format is TAEFormat.DES or TAEFormat.DESR)
                    br.Pad(0x10);

                float startTime = br.GetSingle(startTimeOffset);
                float endTime = br.GetSingle(endTimeOffset);

                if (endTime == float.MaxValue)
                    endTime = EldenRingInfiniteLengthEventPlaceholder;

                Action result = new Action(startTime, endTime);
                br.StepIn(actionDataOffset);
                {
                    result.Type = br.ReadInt32();

                    if (br.VarintLong)
                        result.Unk04 = br.ReadInt32();

                    //if (format == TAEFormat.SDT)
                    //{
                    //    // offset will be 0 in sekiro if no parameters
                    //    br.AssertVarint(br.Position + (br.VarintLong ? 8 : 4), 0);
                    //    parametersOffset = br.Position;
                    //}
                    //else
                    //{
                    //    parametersOffset = br.AssertVarint(br.Position + (br.VarintLong ? 8 : 4));
                    //}

                    // Parameters will ALWAYS be right here otherwise it crashes iirc.
                    parametersOffset = br.GetNextPaddedOffsetAfterCurrentField(br.VarintSize, format is TAEFormat.DES ? 0x10 : 0);
                    br.AssertVarint(parametersOffset, 0);
                    br.Position = parametersOffset;
                }
                br.StepOut();

                return result;
            }
        }

    }
}
