using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;

using SoulsFormats;

namespace SoulsAssetPipeline.Animation
{
    /// <summary>
    /// TAE stands for TimeActEditor. Files with a .tae extension are generated by the internal FromSoft program "TimeActEditor".
    /// They contain TimeAct, a data format defining actions with parameters that happen at specific frames of animations.
    /// The way in which the game associates animation files with the IDs the game references them by is also defined here.
    /// </summary>
    public partial class TAE : SoulsFile<TAE>
    {
        /// <summary>
        /// Which format this file is.
        /// </summary>
        public enum TAEFormat
        {
            /// <summary>
            /// Dark Souls 1.
            /// </summary>
            DS1 = 0,
            /// <summary>
            /// Dark Souls II: Scholar of the First Sin. 
            /// Does not support 32-bit original Dark Souls II release.
            /// </summary>
            SOTFS = 1,
            /// <summary>
            /// Dark Souls III. Same value as Bloodborne.
            /// </summary>
            DS3 = 2,
            /// <summary>
            /// Bloodborne. Same value as Dark Souls III.
            /// </summary>
            BB = 2,
            /// <summary>
            /// Sekiro: Shadows Die Twice
            /// </summary>
            SDT = 3,
            /// <summary>
            /// Demon's Souls
            /// </summary>
            DES = 4,
            /// <summary>
            /// Demon's Souls Remastered
            /// </summary>
            DESR = 5,
        }

        /// <summary>
        /// The format of this file. Different between most games.
        /// </summary>
        public TAEFormat Format { get; set; }

        public bool IsOldDemonsSoulsFormat_0x1000A { get; set; } = false;
        public bool IsOldDemonsSoulsFormat_0x10000 { get; set; } = false;

        public bool HasErrorAndNeedsResave = false;

        public bool SaveWithActionTracksStripped { get; set; } = false;

        public long AnimCount2Value { get; set; } = -1;

        /// <summary>
        /// Whether the format is big endian.
        /// Only valid for DES/DS1 files.
        /// </summary>
        public bool BigEndian { get; set; }

        /// <summary>
        /// ID number of this TAE.
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Unknown flags.
        /// </summary>
        public byte Flags1 { get; set; }
        public byte Flags2 { get; set; }
        public byte Flags3 { get; set; }
        public byte Flags4 { get; set; }
        public byte Flags5 { get; set; }
        public byte Flags6 { get; set; }
        public byte Flags7 { get; set; }
        public byte Flags8 { get; set; }

        /// <summary>
        /// Unknown .hkt file.
        /// </summary>
        public string SkeletonName { get; set; }

        /// <summary>
        /// Unknown .sib file.
        /// </summary>
        public string SibName { get; set; }

        /// <summary>
        /// Animations controlled by this TAE.
        /// </summary>
        public List<Animation> Animations;

        /// <summary>
        /// Version of the action set this file was created with. Can be different within the same game, depending
        /// on when FromSoft saved the file as development progressed (they increase the bank version throughout development).
        /// The game processes all of the files with the same action logic regardless of the action set version,
        /// so the reason this value is stored in the file is unknown.
        /// Not stored in DES/DS1 TAE files.
        /// </summary>
        public long ActionSetVersion { get; set; }

       
        protected override bool Is(BinaryReaderEx br)
        {
            if (br.Length < 4) 
                return false;
            string magic = br.GetASCII(0, 4);
            return magic == "TAE ";
        }

        protected override void Read(BinaryReaderEx br)
        {
            HasErrorAndNeedsResave = false;

            br.BigEndian = false;
            br.VarintLong = false;

            br.AssertASCII("TAE ");

            BigEndian = br.AssertByte(0, 1) == 1;
            br.BigEndian = BigEndian;

            br.AssertByte(0);
            br.AssertByte(0);

            bool is64Bit = br.AssertByte(0, 0xFF) == 0xFF;
            br.VarintLong = is64Bit;
            bool isDESR = false;
            // Demon's Souls Remastered check.
            if (br.GetByte(0x10) == 0x30)
            {
                br.BigEndian = BigEndian = false;
                br.VarintLong = is64Bit = true;
                isDESR = true;
            }


            // 0x1000A: DeS Cut Characters
            // 0x1000B: DeS, DS1(R)
            // 0x1000C: DS2, DS2 SOTFS, BB, DS3
            // 0x1000D: SDT, ER
            int version = br.AssertInt32(0x10000, 0x1000A, 0x1000B, 0x1000C, 0x1000D);

            
            if (version == 0x1000B && !is64Bit)
            {
                Format = TAEFormat.DS1;
            }
            else if (version == 0x1000A && !is64Bit)
            {
                Format = TAEFormat.DS1;
                IsOldDemonsSoulsFormat_0x1000A = true;
            }
            else if (version == 0x10000 && !is64Bit)
            {
                Format = TAEFormat.DS1;
                IsOldDemonsSoulsFormat_0x10000 = true;
            }
            else if (version == 0x1000B && isDESR)
            {
                Format = TAEFormat.DESR;
            }
            else if (version == 0x1000A && isDESR)
            {
                Format = TAEFormat.DESR;
                IsOldDemonsSoulsFormat_0x1000A = true;
            }
            else if (version == 0x10000 && isDESR)
            {
                Format = TAEFormat.DESR;
                IsOldDemonsSoulsFormat_0x10000 = true;
            }
            else if (version == 0x1000C && !is64Bit)
            {
                throw new NotImplementedException("Dark Souls II 32-Bit original release not supported. Only Scholar of the First Sin.");
            }
            else if (version == 0x1000C && is64Bit)
            {
                Format = TAEFormat.DS3;
            }
            else if (version == 0x1000D)
            {
                Format = TAEFormat.SDT;
            }
            else
            {
                throw new System.IO.InvalidDataException("Invalid combination of TAE header values: " +
                    $"IsBigEndian={BigEndian}, Is64Bit={is64Bit}, Version={version}");
            }

            if (isDESR)
            {
                Format = TAEFormat.DESR;
            }

            br.ReadInt32(); // File size
            br.AssertVarint(Format is TAEFormat.DESR ? 0x30 : 0x40);
            br.AssertVarint(1);
            br.AssertVarint(Format is TAEFormat.DESR ? 0x40 : 0x50);

            if (is64Bit && Format is not TAEFormat.DESR)
                br.AssertVarint(0x80);
            else
                br.AssertVarint(0x70);
            
            if (Format is not TAEFormat.DESR)
            {
                if (Format == TAEFormat.DS1)
                {
                    if (IsOldDemonsSoulsFormat_0x1000A || IsOldDemonsSoulsFormat_0x10000)
                    {
                        br.AssertInt16(0);
                        br.AssertInt16(0);
                        Format = TAEFormat.DES;
                    }
                    else
                    {
                        var subFormat = br.AssertInt16(0, 1, 2);
                        if (subFormat == 0)
                            Format = TAEFormat.DES;
                        var test = br.AssertInt16(0, 1);
                        if (test == 0)
                        {
                            HasErrorAndNeedsResave = true;
                        }
                    }
                }
                else
                {
                    ActionSetVersion = br.ReadVarint();
                }

                br.AssertVarint(0);

                if (Format == TAEFormat.DS1 || Format == TAEFormat.DES)
                {
                    br.AssertInt64(0);
                    br.AssertInt64(0);
                    br.AssertInt64(0);
                }
            }



            Flags1 = br.ReadByte();
            Flags2 = br.ReadByte();
            Flags3 = br.ReadByte();
            Flags4 = br.ReadByte();
            Flags5 = br.ReadByte();
            Flags6 = br.ReadByte();
            Flags7 = br.ReadByte();
            Flags8 = br.ReadByte();

            var unkFlagA = br.ReadBoolean();
            var unkFlagB = br.ReadBoolean();

            if (version == 0x1000C)
            {
                if (!unkFlagA && unkFlagB)
                    Format = TAEFormat.SOTFS;
                else if ((unkFlagA && unkFlagB) || (!unkFlagA && !unkFlagB))
                    throw new System.IO.InvalidDataException("Invalid unknown flags at 0x48.");
            }

            for (int i = 0; i < 6; i++)
                br.AssertByte(0);

            ID = br.ReadInt32();

            int animCount = br.ReadInt32();
            long animsOffset = br.ReadVarint();
            br.ReadVarint(); // Anim groups offset

            br.AssertVarint((Format is TAEFormat.DES or TAEFormat.DS1 or TAEFormat.DESR) ? 0x90 : 0xA0);
            var animCount2 = br.ReadVarint();
            if (animCount2 == animCount)
            {
                AnimCount2Value = -1;
            }
            else
            {
                AnimCount2Value = animCount2;
            }
            br.ReadVarint(); // First anim offset
            if (Format is TAEFormat.DS1 or TAEFormat.DES)
                br.AssertInt32(0);
            br.AssertVarint(1);
            br.AssertVarint(Format is TAEFormat.DES or TAEFormat.DS1 or TAEFormat.DESR ? 0x80 : 0x90);
            if (Format is TAEFormat.DS1 or TAEFormat.DES)
                br.AssertInt64(0);
            br.AssertInt32(ID);
            br.AssertInt32(ID);
            br.AssertVarint(Format is TAEFormat.DESR ? 0x40 : 0x50);
            br.AssertInt64(0);



            if (Format is TAEFormat.DES or TAEFormat.DESR)
                br.AssertVarint(0xA0);
            else if (Format is TAEFormat.DS1)
                br.AssertVarint(0x98);
            else
                br.AssertVarint(0xB0);

            long skeletonNameOffset = 0;
            long sibNameOffset = 0;

            if (Format is TAEFormat.DESR)
            {
                br.AssertVarint(0xB0);
                br.AssertInt32(0);
                br.AssertInt32(0);
                //br.AssertInt32(0);
                //br.AssertInt32(0);
            }
            else
            {
                if (BigEndian)
                {
                    if (Format is not TAEFormat.SOTFS)
                    {
                        br.AssertVarint(0);
                        br.AssertVarint(0);
                    }

                    skeletonNameOffset = br.ReadVarint();
                    sibNameOffset = br.ReadVarint();
                }
                else
                {
                    skeletonNameOffset = br.ReadVarint();
                    sibNameOffset = br.ReadVarint();

                    if (Format is not TAEFormat.SOTFS)
                    {
                        br.AssertVarint(0);
                        br.AssertVarint(0);
                    }
                }



                if (Format is not TAEFormat.SOTFS)
                {
                    SkeletonName = skeletonNameOffset == 0 ? null : br.GetUTF16(skeletonNameOffset);
                    SibName = sibNameOffset == 0 ? null : br.GetUTF16(sibNameOffset);
                }
            }

           

            

            br.StepIn(animsOffset);
            {
                Animations = new List<Animation>(animCount);
                bool previousAnimNeedsParamGen = false;
                long previousAnimParamStart = 0;
                for (int i = 0; i < animCount; i++)
                {
                    Animations.Add(new Animation(br, Format, 
                        out bool lastActionNeedsParamGen, 
                        out long animFileOffset, out long lastActionParamOffset));

                    if (previousAnimNeedsParamGen)
                    {
                        br.StepIn(previousAnimParamStart);
                        Animations[i - 1].Actions[Animations[i - 1].Actions.Count - 1].ReadParameters(br, (int)(animFileOffset - previousAnimParamStart));
                        br.StepOut();
                    }

                    previousAnimNeedsParamGen = lastActionNeedsParamGen;
                    previousAnimParamStart = lastActionParamOffset;
                }

                // Read from very last anim's very last action's parameters offset to end of file lul
                if (previousAnimNeedsParamGen)
                {
                    br.StepIn(previousAnimParamStart);
                    Animations[Animations.Count - 1].Actions[Animations[Animations.Count - 1].Actions.Count - 1].ReadParameters(br, (int)(br.Length - previousAnimParamStart));
                    br.StepOut();
                }
            }
            br.StepOut();

            SaveWithActionTracksStripped = false;
            
            // Don't bother reading action tracks in old games.
            // Generate fake meme ones.
            foreach (var anim in Animations)
            {
                // No real action tracks, must generate fakes.
                if (anim.ActionTracks.Count == 0 && (Format is TAEFormat.DES or TAEFormat.DESR or TAEFormat.DS1))
                {
                    SaveWithActionTracksStripped = true;

                    Dictionary<long, ActionTrack> fakeActionTracks = new();

                    foreach (var act in anim.Actions)
                    {
                        int autogenTrackType = act.Type;
                        int autogenTrackSubtype = 0;
                        if (act.Type == 0)
                        {
                            var bin = act.GetParamBinReader(BigEndian);
                            int type0Type = bin.GetInt32(0);
                            autogenTrackType = type0Type;
                        }
                        else if (act.Type == 300)
                        {
                            var bin = act.GetParamBinReader(BigEndian);
                            int type300Type = bin.GetInt16(0);
                            autogenTrackType = type300Type;
                        }
                        long autogenTrackCompositeType = (autogenTrackType * 0x1_00_00_00_00) + autogenTrackSubtype;

                        if (!fakeActionTracks.ContainsKey(autogenTrackCompositeType))
                        {
                            var track = new ActionTrack(act.Type, autogenTrackType, autogenTrackSubtype);
                            fakeActionTracks.Add(autogenTrackCompositeType, track);
                        }

                        act.DS1AutoGeneratedTrack = fakeActionTracks[autogenTrackCompositeType];
                    }

                    // Handle overlapping actions
                    var copyOfActionTracks = fakeActionTracks.Values.ToList();
                    Dictionary<ActionTrack, List<Action>> finalActionTracks = new Dictionary<ActionTrack, List<Action>>();
                    foreach (var track in copyOfActionTracks)
                    {
                        var trackData = track.TrackData;
                        var trackType = track.TrackType;
                        var autogenTrack_Type = track.AutogenTrack_Type;
                        var autogenTrack_Subtype = track.AutogenTrack_Subtype;
                        var actionsInTrack = anim.Actions.Where(ev => ev.DS1AutoGeneratedTrack == track).OrderBy(ev => ev.StartTime).ToList();

                        List<Action> actionsToCommit = new List<Action>();

                        void CommitActions()
                        {
                            if (actionsToCommit.Count > 0)
                            {
                                finalActionTracks.Add(new ActionTrack()
                                {
                                    TrackData = trackData,
                                    TrackType = trackType,
                                    AutogenTrack_Type = autogenTrack_Type,
                                    AutogenTrack_Subtype = autogenTrack_Subtype,
                                }, actionsToCommit);

                                actionsToCommit = new List<Action>();
                            }
                        }

                        for (int i = 0; i < actionsInTrack.Count; i++)
                        {
                            if (i > 0)
                            {
                                var thisAction = actionsInTrack[i];
                                var lastAction = actionsInTrack[i - 1];
                                //Overlap
                                if (thisAction.StartTime < lastAction.EndTime)
                                {
                                    CommitActions();
                                }
                            }

                            actionsToCommit.Add(actionsInTrack[i]);
                        }

                        CommitActions();
                    }

                    copyOfActionTracks.Clear();
                    foreach (var kvp in finalActionTracks)
                    {
                        copyOfActionTracks.Add(kvp.Key);
                        foreach (var act in kvp.Value)
                            act.DS1AutoGeneratedTrack = kvp.Key;
                    }

                    // Sort in .AutogenTrackType order, with 160000 (type 16, blend) coming first.
                    anim.ActionTracks = copyOfActionTracks.OrderBy(x => x.AutogenTrack_Type == (16) ? 0 : x.AutogenTrack_CompositeType + 1).ToList();

                    foreach (var ev in anim.Actions)
                        ev.TrackIndex = anim.ActionTracks.IndexOf(ev.DS1AutoGeneratedTrack);
                }
            }
        }

        protected override void Write(BinaryWriterEx bw)
        {
            bw.WriteASCII("TAE ");

            bw.BigEndian = (Format is TAEFormat.DESR) ? false : BigEndian;

            bw.WriteBoolean((Format is TAEFormat.DESR) ? true : BigEndian);
            bw.WriteByte(0);
            bw.WriteByte(0);

            if (Format is TAEFormat.DESR)
            {
                bw.VarintLong = true;
                bw.WriteByte(0);
            }
            else if (Format is TAEFormat.DES or TAEFormat.DS1)
            {
                bw.VarintLong = false;
                bw.WriteByte(0);
            }
            else
            {
                bw.VarintLong = true;
                bw.WriteByte(0xFF);
            }

            if (Format is TAEFormat.DES or TAEFormat.DS1 or TAEFormat.DESR)
            {
                if (IsOldDemonsSoulsFormat_0x1000A)
                    bw.WriteInt32(0x1000A);
                else if (IsOldDemonsSoulsFormat_0x10000)
                    bw.WriteInt32(0x10000);
                else
                    bw.WriteInt32(0x1000B);
            }
            else if (Format is TAEFormat.DS3 or TAEFormat.SOTFS)
                bw.WriteInt32(0x1000C);
            else if (Format is TAEFormat.SDT)
                bw.WriteInt32(0x1000D);

            bw.ReserveInt32("FileSize");
            bw.WriteVarint(Format is TAEFormat.DESR ? 0x30 : 0x40);
            bw.WriteVarint(1);
            bw.WriteVarint(Format is TAEFormat.DESR ? 0x40 : 0x50);
            bw.WriteVarint(bw.VarintLong && (Format is not TAEFormat.DESR) ? 0x80 : 0x70);

            if (Format is not TAEFormat.DESR)
            {

                if ((Format is TAEFormat.DES or TAEFormat.DS1))
                {
                    if (IsOldDemonsSoulsFormat_0x1000A || IsOldDemonsSoulsFormat_0x10000)
                    {
                        bw.WriteInt16(0);
                        bw.WriteInt16(0);
                    }
                    else
                    {
                        bw.WriteInt16((short)(Format == TAEFormat.DES ? 0 : 2));
                        bw.WriteInt16(1);
                    }
                }
                else
                {
                    bw.WriteVarint(ActionSetVersion);
                }

                bw.WriteVarint(0);

                if (Format is TAEFormat.DES or TAEFormat.DS1)
                {
                    bw.WriteInt64(0);
                    bw.WriteInt64(0);
                    bw.WriteInt64(0);
                }
            }

            bw.WriteByte(Flags1);
            bw.WriteByte(Flags2);
            bw.WriteByte(Flags3);
            bw.WriteByte(Flags4);
            bw.WriteByte(Flags5);
            bw.WriteByte(Flags6);
            bw.WriteByte(Flags7);
            bw.WriteByte(Flags8);

            if (Format is TAEFormat.SOTFS)
            {
                bw.WriteByte(0);
                bw.WriteByte(1);
            }
            else
            {
                bw.WriteByte(1);
                bw.WriteByte(0);
            }

            for (int i = 0; i < 6; i++)
                bw.WriteByte(0);

            bw.WriteInt32(ID);
            bw.WriteInt32(Animations.Count);
            bw.ReserveVarint("AnimsOffset");
            bw.ReserveVarint("AnimGroupsOffset");
            bw.WriteVarint((Format is TAEFormat.DES or TAEFormat.DS1 or TAEFormat.DESR) ? 0x90 : 0xA0);
            bw.WriteVarint(AnimCount2Value >= 0 ? AnimCount2Value : Animations.Count);
            bw.ReserveVarint("FirstAnimOffset");
            if ((Format is TAEFormat.DES or TAEFormat.DS1))
                bw.WriteInt32(0);
            bw.WriteVarint(1);
            bw.WriteVarint((Format is TAEFormat.DES or TAEFormat.DS1 or TAEFormat.DESR) ? 0x80 : 0x90);
            if ((Format is TAEFormat.DES or TAEFormat.DS1))
                bw.WriteInt64(0);
            bw.WriteInt32(ID);
            bw.WriteInt32(ID);
            bw.WriteVarint((Format is TAEFormat.DESR) ? 0x40 : 0x50);
            bw.WriteInt64(0);

            if (Format is TAEFormat.DES or TAEFormat.DESR)
                bw.WriteVarint(0xA0);
            else if (Format is TAEFormat.DS1)
                bw.WriteVarint(0x98);
            else
                bw.WriteVarint(0xB0);

            if (Format == TAEFormat.DESR)
            {
                bw.WriteVarint(0xB0);
                bw.WriteInt32(0);
                bw.WriteInt32(0);
                bw.WriteInt32(0);
                bw.WriteInt32(0);
            }
            else
            {
                if (BigEndian)
                {
                    if (Format != TAEFormat.SOTFS)
                    {
                        bw.WriteVarint(0);
                        bw.WriteVarint(0);
                    }

                    bw.ReserveVarint("SkeletonName");
                    bw.ReserveVarint("SibName");
                }
                else
                {
                    bw.ReserveVarint("SkeletonName");
                    bw.ReserveVarint("SibName");

                    if (Format != TAEFormat.SOTFS)
                    {
                        bw.WriteVarint(0);
                        bw.WriteVarint(0);
                    }
                }



                if (SkeletonName != null)
                {
                    bw.FillVarint("SkeletonName", bw.Position);
                    if (!string.IsNullOrEmpty(SkeletonName))
                    {
                        bw.WriteUTF16(SkeletonName, true);
                        if (bw.VarintLong || Format == TAEFormat.DES)
                            bw.Pad(0x10);
                    }
                }
                else
                {
                    bw.FillVarint("SkeletonName", 0);
                }

                if (SibName != null)
                {
                    bw.FillVarint("SibName", bw.Position);
                    if (!string.IsNullOrEmpty(SibName))
                    {
                        bw.WriteUTF16(SibName, true);
                        if (bw.VarintLong || Format == TAEFormat.DES)
                            bw.Pad(0x10);
                    }
                }
                else
                {
                    bw.FillVarint("SibName", 0);
                }
            }


            

            Animations.Sort((a1, a2) => a1.ID.CompareTo(a2.ID));

            var animOffsets = new List<long>(Animations.Count);
            if (Animations.Count == 0)
            {
                bw.FillVarint("AnimsOffset", 0);
            }
            else
            {
                bw.FillVarint("AnimsOffset", bw.Position);
                for (int i = 0; i < Animations.Count; i++)
                {
                    animOffsets.Add(bw.Position);
                    Animations[i].WriteHeader(bw, i, Format);
                }
            }

            // foreach (var anim in Animations)
            // {
            //     if (SaveWithActionTracksStripped)
            //         anim.ActionTracks.Clear();
            // }


            bw.FillVarint("AnimGroupsOffset", bw.Position);
            bw.ReserveVarint("AnimGroupsCount");
            bw.ReserveVarint("AnimGroupsOffset");
            if (Format == TAEFormat.DES)
                bw.Pad(0x10);
            int groupCount = 0;
            long groupStart = bw.Position;
            for (int i = 0; i < Animations.Count; i++)
            {
                int firstIndex = i;
                bw.WriteInt32((int)Animations[i].ID);
                while (i < Animations.Count - 1 && Animations[i + 1].ID == Animations[i].ID + 1)
                    i++;
                bw.WriteInt32((int)Animations[i].ID);
                bw.WriteVarint(animOffsets[firstIndex]);
                if (Format == TAEFormat.DES)
                    bw.Pad(0x10);
                groupCount++;
            }
            bw.FillVarint("AnimGroupsCount", groupCount);

            if (groupCount == 0)
                bw.FillVarint("AnimGroupsOffset", 0);
            else
                bw.FillVarint("AnimGroupsOffset", groupStart);

            if (Animations.Count == 0)
            {
                bw.FillVarint("FirstAnimOffset", 0);
            }
            else
            {
                bw.FillVarint("FirstAnimOffset", bw.Position);
                for (int i = 0; i < Animations.Count; i++)
                    Animations[i].WriteBody(bw, i, Format);
            }

            for (int i = 0; i < Animations.Count; i++)
            {
                Animation anim = Animations[i];
                anim.WriteAnimFile(bw, i, Format);
                Dictionary<float, long> timeOffsets = anim.WriteTimes(bw, i, Format);
                List<long> actionHeaderOffsets = anim.WriteActionHeaders(bw, i, timeOffsets, Format);
                anim.WriteActionData(bw, i, Format);
                anim.WriteActionTrackHeaders(bw, i, Format, SaveWithActionTracksStripped);
                anim.WriteActionTrackData(bw, i, actionHeaderOffsets, Format);
            }

            bw.FillInt32("FileSize", (int)bw.Position);
        }

    }
}
